# Generated by Django 5.2.3 on 2026-06-15 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emergency", "0003_safetytip"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guidance", models.TextField()),
                ("generated_message", models.TextField()),
                ("translated_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emergency.emergencyreport",
                    ),
                ),
            ],
        ),
    ]
