# Generated by Django 5.2.3 on 2026-06-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0002_emergencyreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("tip", models.TextField()),
            ],
        ),
    ]
