# Generated by Django 5.2.3 on 2026-06-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0003_safetytip"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencycontact",
            name="user_id",
            field=models.CharField(db_index=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emergencyreport",
            name="user_id",
            field=models.CharField(db_index=True, default="unkown", max_length=255),
            preserve_default=False,
        ),
    ]
