# Generated by Django 5.2.3 on 2026-06-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0005_alter_emergencycontact_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencyreport",
            name="user_id",
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
